configfile: "config/config.yaml"

# TODO add final output
rule all:
    

rule hd_bet:
    input:
        "T1_W_post/{subject}/Post_{subject}.nii.gz"
    output:
        "T1_W_post/T1_Brain/Post_{subject}_brain"
    conda:
        "envs/hd_bet.yaml"
    shell:
        "hd-bet -i {input} -o {output} -tta 0 -mode fast -device cpu"

rule convert_pre_denoise:
    input:
        data="bids/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.nii",
        bvecs="bids/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.bvec",
        bvals="bids/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.bval"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.mif"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "mrconvert {input.data} -fslgrad {input.bvecs} {input.bvals} {output}"

rule denoise:
    input:
        dwi="bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.mif",
        noise="bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_noise.mif"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi_denoise.mif"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "dwidenoise {input.dwi} {output} -noise {input.noise}"

rule convert_post_denoise:
    input:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi_brain_mask.nii.gz"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi_mask.mif"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "mrconvert {input} {output}"

rule bias_correction:
    message: "Bias field correction"
    input:
        data="bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi_denoise.mif",
        mask="bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi_mask.mif",
        bias="bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_bias.mif"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbc.mif"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "dwibiascorrect fsl {input.data} {output} -mask {input.mask} -bias {input.bias}"

rule ringing_correction:
    message: "Ringing artifact correction"
    input:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbc.mif"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbcdegibbs.mif"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "mrdegibbs {input} {output}"

rule convert_post_ringing:
    input:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbcdegibbs.mif"
    output:
        "bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbcdg.nii.gz"
    container:
        "docker://mrtrix3/mrtrix3:3.0.4"
    shell:
        "mrconvert {input} {output}"

# TODO convert as a rule
# singularity run -e \
# -B /eresearch/resmed/mtay316/DTI/Concussion_Phase2/Preseason/Processing/b0_synth/INPUTS/Pre_{subject}:/INPUTS \
# -B /eresearch/resmed/mtay316/DTI/Concussion_Phase2/Preseason/Processing/b0_synth/OUTPUTS/Pre_{subject}:/OUTPUTS \
# -B /eresearch/resmed/mtay316/DTI/Concussion_Phase2/Preseason/Processing/b0_synth/license.txt:/extra/freesurfer/license.txt \
# /hpc/mtay316/B0_synth/synb0-disco_v3.0.sif

# NOTE: Remeber to put the index.txt and acqparams.txt files in the right folder

# TODO convert as a rule
# echo "Eddy current correction"
# scp DWI_W_pre/sub-{subject}_ses-{session}_Pre/index.txt BIDS_Processing/Pre_{subject}
#eddy_cuda9.1 --imain=bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwidnbcdg.nii.gz --mask=bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/dwi_brain_mask_{subject} --index=bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/index.txt --acqp=b0_synth/INPUTS/acqparams.txt --bvecs=bids/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.bvec --bvals=bids/sub-{subject}/ses-{session}/dwi/sub-{subject}_ses-{session}_dwi.bval --fwhm=0 --topup=b0_synth/OUTPUTS/Pre_{subject}/topup --flm=quadratic --cnr_maps --out=bids/derivatives/dwi_preprocessing/sub-{subject}/ses-{session}/dwi/eddy_unwarped_{subject} --repol --mporder=6 -v
